Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Compartilhamento da pasta html local com a VM
  config.vm.synced_folder "C:/Users/Usuario/Documents/Vinicius/Repositórios - github/Udemy/DevOps/2_Vagrant/vagrant-lab/html", "/vagrant/html", type: "virtualbox"

  config.vm.provision "shell", path: "provision.sh"
end
