---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  var_files:
    - vars/main.yml
  vars:
   - dbname: "db01"
   - dbusername: "root"
   - db_password: "devops"
  tasks:
   - name: "Configurar hosts lab ansible"
     lineinfile: line "{{item}} path=/etc/hosts"
     with_items:
       - 192.168.56.10 control-node
       - 192.168.56.11 app01
       - 192.168.56.12 db01
  roles:
   - configuracao-default-so
   - role: geerlingguy.mysql
   