Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.network "forwarded_port", guest: 80, host: 1234
  config.vm.provision "shell", path: "provision.sh"
end
